### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by MarinaMarissa** [Metroite/iris-explorer#1]
[latest.log](https://github.com/Metroite/iris-explorer/files/6216951/latest.log)
im using https://github.com/IrisShaders/Iris/commit/df5988a1c4b7ee343f5661447ca80cd2465e0677 and https://github.com/IrisShaders/sodium-fabric/commit/e0369669aed994ce6085e319d348d15af4c15a3a

**Comment by metroite** [comment]
Thanks for the report. Fixed in 11a035457a97b87691f44c1fdad8405d926b33c3.
